blank_issues_enabled: false
contact_links:
  - name: 401 Unauthorized Errors?
    url: https://github.com/samrum/OnStarJS/issues
    about: Please refer to OnStarJS for API issues
  - name: Other Issues and Feature Requests
    url: https://github.com/samrum/homebridge-onstar/issues/new
    about: Create a new issue here
